name: Merge Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read        # Permite leer el contenido del repositorio
  pull-requests: write  # Permite escribir y modificar pull requests
  issues: write         # Permite interactuar con issues (comentarios, crear, etc.)
  actions: read         # Permite leer el estado de las acciones de GitHub

jobs:
  go:
    runs-on: ubuntu-latest
    services:
        postgres:
            image: postgres
            env:
              POSTGRES_USER: postgres
              POSTGRES_PORT: 5432
              POSTGRES_DB: postgres
              POSTGRES_PASSWORD: postgres
              DB_HOST: localhost

            # Set health checks to wait until postgres has started
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
            ports:
              # Maps tcp port 5432 on service container to the host
                - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: stable

      - name: install dbmate
        run: |
          curl -fsSL https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-amd64 -o dbmate
          chmod +x dbmate
          sudo mv dbmate /usr/local/bin/

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: /tmp/go-build
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-
      - name: Format code
        run: make fmt
      - name: up test database
        run: make db-test-up
      - name: Run tests
        run: make test